### ISSUE TITLE
Test for Rotem

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#11]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
You have been assigned as project manager for a project for the client Kuno Corp (your client stakeholder is Leo). The outcome of this project will be a website which allows a user to sign up, and log-in to a system that gives them real-time sales rankings for their salesmen. The system as a whole is expected in 8 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for login and signup as well as the frontend for real-time sales rankings information - This will be handled by Wiredcraft completely
• the backend for real-time sales rankings information which will be provided by a separate company Jhonny Labs, you will need to interface with Frank, their project manager, to coordinate as they are building this system from scratch for Kuno Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the real-time sales rankings information system expects to receive the Username and Email so they can customise the information in the backend for WCL to access and display in the front-end.

In your team you have:
• Two designers who can make mockups and flow diagrams of the login and once confirmed, implement the frontend parts.
• A developer who can implement the backend and help out integrating the login/sales rankings frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Jhonny Labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@leo111) and real-time sales rankings service vendor (@flfrank222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@leo111 - I heard from FLFrank222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by rotemsioni** [comment]
@flfrank222 Hi Frank, hope everything is well. I'd like to schedule time for a technical workshop with you to discuss the integration points and data flow. I'm assuming WD will use Jhonny Lab APIs? Do you have any specs drafts you can share in the meanwhile? 
@LEO111 Hi Leo, I'm planning to schedule a technical workshop with Frank and his team. Would you like to join as well? The agenda will be to discuss integration points and data flow

**Comment by mpathiuk** [comment]
Hi @rotemsioni we can keep this a little more high level.Assume you have received the API specs from @flfrank222 and all tech handover has happened with your team and the client involved.

**Comment by rotemsioni** [comment]
@mpathiuk 
Hi Mik, I can't upload the file here so I sent it by email.  
Let me know if you have any feedback, thanks!

**Comment by mpathiuk** [comment]
[Proposal for Kuno Corp.pdf](https://github.com/Wiredcraft/test-pm/files/1500426/Proposal.for.Kuno.Corp.pdf)

Uploading received project plan here for visibility.

**Comment by mpathiuk** [comment]
@rotemsioni We're now in week 2 of your plan, and so far things are going well. In the middle of week 2 you get the following message from @flfrank222 of Jhonny Labs:

HI @rotemsioni , we've just found out that due to a new government regulation, we now need to receive the phone number of a user during registration (validated through SMS) before we can share any data with them. Please can you implement this on the frontend and pass the phone number to us along with username and email?

You have a quick meeting with your team and you find out the following:
• Implementing SMS validation would be 2 more weeks of work (including testing and UAT time) 
• The team checks the various options, and reviews the new government regulation which comes into effect 2 weeks after the scheduled launch. Your team suggests to launch as planned, and implement SMS validation and launch that 2 weeks later.

What do you do next?

**Comment by rotemsioni** [comment]
First I‘ll contact Frank and ask him if his team can complete the SMS validation related work on their side within two weeks so we can be sure to launch this feature before the regulations come into effect. I will also have a short workshop to understand exactly the flow and the division of work between the two service providers. 

After Frank’s confirmation, I’d contact Leo and present to him the new requirement with two potential solutions:

**Option A**: Launch the website as planned and implement the SMS validation two weeks after. 
_Impact_:
- The new feature will be added after two weeks, might cause inconvenient to business. 
- Adding the phone verification will increase website security, if we lunch the website without this feature the user might use a wrong phone number or a phone number of anther user. 

_Benefit_: 
- No impact on the timeline 

_Risks_: 
- Timeline is quite tights, if something goes wrong there is a slight chance the website will be released and won’t support the government regulation on time. 

**Option B**: Launch the website two weeks after schedule 
_Impact_: 
- Two weeks delay in delivery. 

_Benefits_:
- Increase website security and safer approach to ensure alignment with government regulations. 

I’ll explain to the client that it is very important to aligned with the Chinese government regulations and that we can’t ignore this requirement even if it means additional time and cost. I will apologize for not consider this requirement earlier during the planning phase. 

In the same time, additional 2 more weeks of work is required, I’ll share the exact number of MD that we will need to charge (Including design, development, PMO and QA) with the Client Manager to see how to manage the client and the budget. I'll also check if there is any clause in the contract that refers to delay in timeline and work together with the Client Manager to find a win-win solution with the client.

**Comment by mpathiuk** [comment]
Assume the client has chosen to go with Option B above. Everything has been cleared with the PMO and client manager on the budget side and you have committed to release 2 weeks later with SMS validation. 

You're now 1.5 weeks away from delivery when two of your team members fall ill. The remaining team members will not be able to finish all the work by the end of week as planned. Frank also confirms that there is no delay from the Jhonny Labs side. What do you do now.

**Comment by rotemsioni** [comment]
In this case, I would have three options: 
A. Contact backup outsource service providers to see if they can help out with the pending items.
B. Contact Jhonny Labs to see if perhaps they can finish the development of the pending items, or at least help with small tasks. 
C. Communicate with my team members and ask them to do overtime once they are back to the office in order to complete all pending items on time. I will also ask them if possible to work from home for less OT during the end of the week.

Although those three options would allow us to deliver on time, there are a few elements to consider:
- All options come with additional cost (To outsourcing, to Jhonny Lab or as OT pay), I will need approval of management. 
- The quality of the outsourcing work might be a big risk, and they are not familiar with the project and aren't fully committed to the project.
- Jhonny Lab may not be an expert of FE development. 
- OT may impact the team morale and relations.

No matter which option will be chosen, I would be transparent with the client and keep them in the loop of every step. Of course I would ask them if a delay in delivery could be acceptable. If not, I will proceed with the three options to see which one has the best value for money. If yes, I would prefer to wait until my team member are back to the office and not compromise on the development quality.

**Comment by mpathiuk** [comment]
Thank you, we have enough information to continue, closing this test as completed.
