### ISSUE TITLE
Test for Guido

### ISSUE THREAD

**Issue by fuzhuang** [Wiredcraft/test-pm#17]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
On behalf of Wiredcraft (WCL), you have been assigned as project manager for a project for the client DESCO Corp (your client stakeholder is Karen). The outcome of this project will be a Wechat miniapp which enables user to scan items in store and pay for it through Wechat. The system as a whole is expected in 10 weeks.

**Project Details**
The work has been divided into two parts:
• the frontend for wechat miniapp and backend to support data integration with store core system will be handled by Wiredcraft completely
• the backend for store inventory management and POS are provided by a separate company Retail Genius Ltd, you will need to interface with Bob, their project manager, to coordinate as they are running this system for DESCO Corp.

The specific requirements for basic flow has been established as below:
User could scan QRcode to access the app;
User could click "scan" button in app to enable the camera to scan product barcode in store;
User could add the product items scanned into cart;
User could edit the cart before payment and be able to pay from cart.

In your team you have:

• One designer to make wireframe and mockups to confirm detail flow and UX.
• Two frontend developeres who can make mockups and flow diagrams and once confirmed, implement the frontend parts.
• A developer who can implement the WCL backend and help out integrating with store core systems
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Retail Genius Ltd up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@Kar11) and the coupons service vendor (@bbob222) ) and you can @myteam333 for questions to your development team)

e.g.
@Kar11 - Hi there, can I confirm with you the requirements for ...
@bbob222- I heard from @Kar11 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@fuzhuang - For the test, I don't understand what you mean by xxx ...

**Comment by GuidovMal** [comment]
@team333 - Hi Team. For the front end developers I will contact Karen and get their corporate layout like logo, colour scheme etc.

**Comment by GuidovMal** [comment]
@Kar111 - Hi Karen, Hope you are well. I have posted a initial project plan on Github: https://github.com/GuidovMal/Desco
You can download the project plan from there or I am happy to email you a copy. Look forward to any comments. Once you have reviewed I suggest we all get together to go through the stages of the project. 
Thank you,
Guido

**Comment by GuidovMal** [comment]
@Kar111 - Hi Karen. Would you be able to provide Desco's corporate layout for our front end developers? Information like company logo, colour scheme, fonts would be appreciated.
Thanks again,
Guido

**Comment by GuidovMal** [comment]
@team333 - Hi Team. For the future planning of the project I would like to try to use Yodiz. It is a great online project tool for agile projects. We can integrate into Github. Of course I will discuss with Fuzhuang if she agrees with this approach. I would be happy to share a concept with you first. Thank Guido

**Comment by GuidovMal** [comment]
@Kar111 - Hi Karen. In regards to the requirement to use the camera to scan a product barcode could you specify what information you would like to be displayed on the product page? This is important for the interface with Retail Genius. Product information could be product code, description, price, quantity and perhaps image. 
Thanks again,
Guido

**Comment by fuzhuang** [comment]
Test done. Closing.
