### ISSUE TITLE
Test for Luna

### ISSUE THREAD

**Issue by fuzhuang** [Wiredcraft/test-pm#18]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
On behalf of Wiredcraft (WCL), you have been assigned as project manager for a project for the client WMM Corp (your client stakeholder is Anna). The outcome of this project will be a H5 app which help user to search product and find items in the store in the app. The system as a whole is expected in 10 weeks.

**Project Details**
The work has been divided into three parts:
• the frontend for making the map view, backend to support data integration with store core system to show inventory and price and the search component. All will be handled by Wiredcraft completely.
• the store core system and POS are provided by a separate company SuperTech Ltd, you will need to interface with James, their project manager, to coordinate as they are running this system for WMM Corp.

The specific requirements for basic flow has been established as below:
User could search products by keywords in the app;
User could view product details from search result list in store, including price and inventory;
User could check the location of the product in store map.

In your team you have:

• One designer to make wireframe and mockups to confirm detail flow and UX.
• 2 frontend developeres who can make mockups and flow diagrams and once confirmed, implement the frontend parts.
• 3 backend developers who can implement the WCL backend and help out integrating with store core systems
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Retail Genius Ltd up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@Anna111) and the coupons service vendor (@James222) ) and you can @myteam333 for questions to your development and design team)

e.g.
@Anna 111 - Hi there, can I confirm with you the requirements for ...
@James222- I heard from @Anna111 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@fuzhuang - For the test, I don't understand what you mean by xxx ...

**Comment by chrimare** [comment]
@fuzhuang unlucky, I don't have any exp for H5 APP, what I wrote below is based on my methodology.  For the breakdown task, I assume that you mean breakdown the whole project. please let me know if you have any problems, thanks.

**Task 1**
WCL will need to provide client a H5 APP with following items within 10 weeks:
1. check function for product location in store map and design store map view
2. search function for product by keyword
3. display function for product info, including inventory and price（data integration with store core system vendor)

**Task2**
work breakdown
-for UI part, the task would be H5 APP mockup, home page/search page/display page display, button & icon display, loading display, list display, map view
-for frontend part, mockups, flow diagrams, home page display(include location of each function), transition page display and logic, map view design and result display, search page and result list display, product info display 
-for backend part, check and confirm 3rd party's interface and system and how the data works, match the external and internal data interface, design the data integration flow with store core system, data management and transition, help out the internal function to call the data
-for deployment part, set up servers and deployment for each function 

Phase I mockup version(w1) - confirm the requirements and mockup design with client
in the first week, WCL should review the requirements and make sure all team members on the same page. Raise any inapproriate part to client at the beginning and confirm the final requirement, then provide the mockup version to client based on the requirement and scope. Get confirm from client and then move on to next stage. 

Phase II draft version(w2-4) - deliver the basic function
based on the priority and tasks, during these 3 weeks, the team could provide the basic look of the APP and basic operation function without the data

Phase III update version(w5-8) - update the version based on client feedback
during this period, the data could be integrated and the functions would be updated based on client's feedback. within the scope, the version could be updated weekly to get quick confirm from client. need cooperation from client to do some UAT test.

Phase IV final version(w9-10) - H5 APP final delivery 
at the end, no more new requirements and WCL will polish the APP to make sure it ready for launch.

daily operation for project
1. every Monday morning, quick update for last week and propose plan for this week, list the high priority tasks and make sure each member pick their tasks, solve the problem if any
2. communicate with 3rd party or client if needed
3. daily quick update from member before end of the day and update the project progress

**Comment by fuzhuang** [comment]
Closing as done.
