### ISSUE TITLE
Test for Libo Sheng

### ISSUE THREAD

**Issue by fuzhuang** [Wiredcraft/test-pm#20]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
On behalf of Wiredcraft (WCL), you have been assigned as project manager for a project for the client DESCO Corp (your client stakeholder is Karen). The outcome of this project will be a Wechat miniapp which enables user to scan items in store and pay for it through Wechat. The system as a whole is expected in 10 weeks.

**Project Details**
The work has been divided into two parts:
• the frontend for wechat miniapp and backend to support data integration with store core system will be handled by Wiredcraft completely
• the backend for store inventory management and POS are provided by a separate company Retail Genius Ltd, you will need to interface with Bob, their project manager, to coordinate as they are running this system for DESCO Corp.

The specific requirements for basic flow has been established as below:
User could scan QRcode to access the app;
User could click "scan" button in app to enable the camera to scan product barcode in store;
User could add the product items scanned into cart;
User could edit the cart before payment and be able to pay from cart.

In your team you have:

• One designer to make wireframe and mockups to confirm detail flow and UX.
• Two frontend developeres who can make mockups and flow diagrams and once confirmed, implement the frontend parts.
• A developer who can implement the WCL backend and help out integrating with store core systems
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Retail Genius Ltd up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@Kar111) and the coupons service vendor (@bbob222) ) and you can @myteam333 for questions to your development team)

e.g.
@Kar1111111 - Hi there, can I confirm with you the requirements for ...
@bbob222- I heard from @Kar1111111  that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@fuzhuang - For the test, I don't understand what you mean by xxx ...

**Comment by fuzhuang** [comment]
@Kar111 Could you delete and ignore? Thanks

**Comment by shenglibo** [comment]
@fuzhuang - For the test, so far I have two questions as,
1. We need to provide the Wechat miniapp for 0 to 1, or just add the 'scan' function to current app?
2. how long about each sprint?

**Comment by shenglibo** [comment]
@fuzhuang - For the test, first of all, I want to get some information about the project status and our my team as blow:
1.	We need to provide the Wechat miniapp for 0 to 1, or just add the 'scan' function to current app?
2.	how long about each sprint?

**Comment by fuzhuang** [comment]
@shenglibo Hi, for your questions:
1. We don't have the app yet so yes it's 0->1.
2. We have no hard limit on that, you could plan it as you see fit.

**Comment by shenglibo** [comment]
@fuzhuang Thanks,  since it's a 0->1 project, we need a product manager to provide the PRD and system prototype, if the designer in my team can finish this part, that will be OK too. 

Also, we need at least one tester to make sure the outcome reaches client's requiement and has no critical bug.

**Comment by fuzhuang** [comment]
@shenglibo Let's assume the designer is doing this part, pls go ahead with your plan.

**Comment by shenglibo** [comment]
@bbob222- I heard from @Kar1111111 that they need to have a new function as 'scan' , means users can add products into cart by scanning product barcode in store. I'm not clear on how store inventory management and POS work, can you tell me more about it?
Based on my current understanding,I think we need to change/add several interfaces between WCL and your system, include several sides:
1.product inventory sync interface
2.order sync interface
3. payment sync interface 

how do you think about it?

Thanks.

**Comment by Kar111** [comment]
Please don't send me these messages. )))

**Comment by fuzhuang** [comment]
Test done. Closing.
