### ISSUE TITLE
Test for Jerry Zang

### ISSUE THREAD

**Issue by fuzhuang** [Wiredcraft/test-pm#22]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
You have been assigned as project manager for a project for the client Zbal Corp (your client stakeholder is Vincent). The outcome of this project will be a web app which allows a user to sign up, and log-in to a system that gives them a data dashboard for climate figures. The system as a whole is expected in 5 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for login and signup as well as the frontend for climate data display - This will be handled by Wiredcraft completely
• the backend for climate data information which will be provided by a separate company Qingfeng Labs, you will need to interface with Song, their project manager, to coordinate as they are building this system from scratch for Zbal Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the real-time climate data system expects to receive the Username and Email so they can customise the information in the backend for WCL to access and display in the front-end the correct data for this user.

In your team you have:
• Two designers who can make mockups and flow diagrams of the login and once confirmed, implement the frontend parts and dashboard.
• A developer who can implement the backend and help out integrating the login/data dashboard figure frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Qingfeng Labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@Vincent121111) and real-time climate data service vendor (@Song222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@Vincent121111 - I heard from Song222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@fuzhuang - For the test, I don't understand what you mean by xxx ...

**Comment by Jerry-zang** [comment]
**Requirement：**
This project is to develop a web app, users need to sign up in this app by their user name, password and email, after that, they can sign in the app, and they will see a dashboard of the climate. One thing we need to know is that the climate data will be provided by another company Qingfeng Labs, that means we have to develop a interface with them.
**Final scope：**
The tasks for us wriedcraft have 2 parts: software and hardware, include environment, frontend and backend.
For the frontend, we need to provide 3 interfaces for users: sign up interface, sign in interface and the interface to display the dashboard of climate.
For the backend, we need to provided:
    1.A database to store the user information when they register the app and the login information when they sign in.
    2.Three service: sign up, sign in and climate data, so the fronted could invoke these three services.
For the interface with Qingfeng Labs, we need arrange a meeting with Song and Vincent, to discuss the details and the definition of the interface, and what's more, who should be accountable for this interface.
**WBS:**
1.Project Management
   1.1 Plan
        1.1.1 Project plan
        1.1.2 Weekly plan
    1.2 Communication
        1.2.1 Internal communication
        1.2.2 External communication
    1.3 Meeting
        1.3.1 Kick-off meeting
        1.3.2 Planning meeting
        1.3.3 Review meeting
        1.3.4 Retrospective meeting
        1.3.5 Stand-up meeting
        1.3.6 Temporary meeting
    1.4 Request
        1.4.1 Request investigation
        1.4.2 Request analysis
    1.5 Resource
        1.5.1 Development team
        1.5.2 Others
2.Software
    2.1 Frontend
        2.1.1 Interface Design
            2.1.1.1 Sign up interface
            2.1.1.2 Sign in interface
            2.1.1.3 Dashboard interface
        2.1.2 Interface development
            2.1.1.1 Sign up interface
            2.1.1.2 Sign in interface
            2.1.1.3 Dashboard interface
    2.2 Backend
        2.2.1 Service
            2.2.1.1 Service design
                2.2.1.1.1 Sign up service
                2.2.1.1.2 Sign in service
                2.2.1.1.3 Dashboard service
            2.2.1.2 Service development
                2.2.1.2.1 Sign up service
                2.2.1.2.2 Sign in service
                2.2.1.2.3 Dashboard service
        2.2.2 Database
        2.2.3 Interface
                2.2.3.1 Interface discussion
                2.2.3.2 Interface design
                2.2.3.3 Interface development
3.Hardware
    3.1 Server
    3.2 Environment
        3.2.1 Test environment
        3.2.2 Production environment

**Comment by Jerry-zang** [comment]
**Project Plan:**
We'll have a kick-off meeting in the first week, and in the whole project, will have milestones: kick-off meeting in the first week, mockups of the app in the second week, initial app in the third week, integrated app in the fourth week and the final app in the fifth week.
1st Week:
    Make the design of the sign up, sign in and dashboard interface
    Design the backend services
    Arrange the meeting to confirm the interface with Qingfeng Lab.
    Investigate the function detail with Vincent.
    Confirm the interface design with Vincent.
Deliverables:
    The design of three interfaces(sign up, sign in & dashboard)
    Services design
    The interface definition between us and Qingfeng Labs
    Request analysis report
2nd week:
    Amend the design as user's request
    Develop the mockups of sign up, sign in & dashboard interface
    Develop three backend service and test them
    Develop the database to store the user information and sign in information
    Design the interface for Qingfeng Labs if confirmed it should be down by us in sprint 1
    Confirm the mockup with Vincent
Deliverables:
    The mockups of three interfaces
    Three backend services
    Design of the interface with Qingfeng Labs
3rd week:
    Amend the mockups as user's request
    Deploy the test environment and database
    Frontend invoke backend service
    Develop the interface with Qingfeng Labs and internal test it.
    Confirm the function of signing up, signing in and dashboard with Vincent
Deliverables:
    The environment for test
    Test script
    A initial web app
    Interface with Qingfeng Labs
4th week:
    Integration test with Qingfeng Labs
    UAT
Deliverables:
    Web app that can satisfy the request
    UAT record
5th week
    Fix bugs
    Trace and improve the user experience
    Transfer the knowledge, documents and others
Deliverables
    The final web app
    Project documents
**Project Management:**
Every Monday, we will have a planning meeting to confirm the goal and the backlog of this week and then quickly estimate the job together
I will make the burn down chart every week to monitor the process
We will have a short stand-up meeting every morning, within 15 minutes, quickly go through "what I've down", "what I am going to do" and "the trouble I've got"
After review meeting with users, we will have an internal retrospective meeting to discuss the work of this week
**Communication:**
Internal communication: we will work in the same office so just ask to your teammate, and I will create a group chat in wechat so we can share the documents or ideas in there.
External communication: we will have a review meeting with users every week, besides, if you have any issue need to confirm with users, you can send email to them just please remember CC to me, or you can directly make a concall with them, do not forget send email to confirm the conversation content after that. For Qingfeng Lab, similarly, we will have weekly meeting with them to communicate the process, you can also send to email or make a concall for urgent issue.

**Comment by Jerry-zang** [comment]
@Vincent121111 
Dear Vincent,
     Good afternoon, I hope this message finds you well.
      We'll start the Zbal Corp climate web app project soon, before that, I hope we can arrange a kick-off meeting next week,  the meeting will have 3 subjects:
1. Introduce the project, including background, goal, milestone, plan and etc.
2. Introduce the team members and key users to each other.
3. Declare the start of the project.

      The meeting will be about 90 mins, please let me know when you and our key users will be available next week, and I would be appreciated if you could help to reserve a meeting room for us, we have 5 people here, thank you very much.
      Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by Jerry-zang** [comment]
@song222
Dear song,
        Good afternoon, this is Jerry, project manager of Zbal Corp climate web app project from wiredcraft, hope this message finds you well.
        We will start the project next week, and there is an important interface between us. About this interface, I think there is still a lot of details we need to confirm, so could you please tell me when you will be available next week, so we can have a meeting to discuss them, Mr.Vincent will be invited also.
         Thanks and Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by Jerry-zang** [comment]
@myteam333
Dear all,
Good afternoon, this is Jerry, project manager of Zbal Corp climate web app project, hope this message finds you all well.
I think you are already informed that we will start a new project next week, it's my pleasure to work with you guys, hope we could have a good cooperation. I just upload a rough project plan in comment, please check it and I would be appreciated if you have any opinion and suggestion about it, thanks!
What's more, we will have a kick-off meeting next week, I'll let you know once the time is confirmed, look forward to seeing you next week!
Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by Jerry-zang** [comment]
@fuzhuang
Dear fuzhuang, 
        I just finished the test, sorry to spend too much time.
        In this project, I refer to the scrum methodology and the project I experienced before, for many details, I choose to arrange meetings to discuss them rather than ask questions by comments, because I think face-to-face is the most effective method to communicate. 
        I know there must be some defect, and I am really looking forward your opinion so that I can know where I still need to be improved, thank you very much!
        Best Regards!

**Comment by fuzhuang** [comment]
Hi @Jerry-zang , Thanks for the project plan and all the emails, I will be mocking for some of the scenarios in the project and pls update here as you are using GH to manage the project.

**Comment by fuzhuang** [comment]
@Jerry-zang It is now in the middle of week 3, and @song222 just tell you that due to their other parallel project, they have a major update in the API design, and they will send you the updated API specs when it's finalized internally.

**Comment by Jerry-zang** [comment]
@fuzhuang 
Hi Fuzhuang, thanks for the scenario! 
For this scenario, I have 3 actions here:
1.I need to make a urgent meeting with Song to get more information about this change, include the reason and background, if the update is necessary or not, how long will this update cost and etc.
2.I need my team's help to estimate the impact to our interface of this update: just need to some small change or we have to re-develop a total new one, then I need to make some change of our project plan based on the estimation.
3.I will tell Vincent the result of communicatrion and estimation, let he know the probable impact and see his attitude of this issue.
And I will write the emails in the following comments, please check them, thanks!

**Comment by Jerry-zang** [comment]
@song222
Dear Song,
Good afternoon! 
Thanks for the information, but I have a few questions about your update, can we have a concall meeting soon? So our team could know more about this update and make some strategy to ensure the project process. 
Please let me know when you are available, thank you very much!
Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by Jerry-zang** [comment]
@Vincent121111
Dear Vincent,
Good afernoon!
I just got a information from Mr.Song, they will have a major update in API design and that might make some impact on our project. I just ask a urgent meeting with Mr. Song to get more information and estimate the impact, so please know this issue, and I will report the result to you when we finalize it, thank you!
Please feel free to let me know if there should be any question.
Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by fuzhuang** [comment]
@Jerry-zang Vincent is very upset about the change, he told you that internally the launch date has been communicated across different departments, mkt and operations and so on, so he pushed you to have the team working OT to cover the time loss.

**Comment by Jerry-zang** [comment]
@fuzhuang
Hi Fuzhuang, thanks for your reply!
In this case, I think the first thing is to pacify Vincent, tell him the change may not cause any big impact for us, we are still estimating the change, and we will have different solutions for the estimation results.
I''ll put the email to Vincent in the following, please check it, thanks!

**Comment by Jerry-zang** [comment]
@Vincent121111
Dear Vincent,
Good morning!
Thanks for your kindly information! We know the launch date is very important, we won't postpone it unless necessary and we don't have any other choice, so please don't be worried about that, we will make it on time.
Now my team are estimating the impact of the change, I am not sure how far the change will impact us, but we will have different solutions for the estimation results, and I can promise you that we will work overtime to ensure the launch date if OT is useful for our schedule, please don't be upset, all is well.
Please feel free to let me know if there should be any question.
Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by fuzhuang** [comment]
@Jerry-zang Usually we don't encourage our team to do overtime unless it's absolutely needed. In this case, the delay is not caused by our side, could you try some alternative communication other than promise the client that we will do OT?

**Comment by Jerry-zang** [comment]
@fuzhuang 
Hi Fuzhuang, Thanks for your kindly reply!
I totally agree with you about the OT, and I am sorry I misunderstand the scenario and use some inappropriate words in the last email. I will update the new email in the following comment, please check it, thanks!

**Comment by Jerry-zang** [comment]
@Vincent121111
Dear Vincent,
Good afternoon!
Thanks for your kindly information!
Now we are implementing the project as our schedule, we also think this change may cause some risk for our process. Could you please push them to complete the update as soon and provide us the API as the schedule we confirmed before? Or maybe you could ask them to suspend the update until our app is launched, then we can make sure the app will be launched on time, thank you very much! 
Please feel free to let me know if there should be any question.
Best Regards!

Wiredcrafted Zbal Corp climate web app project
Project manager-Jerry
Email: Jerryforzl@126.com
Tel:+86 15610535625

**Comment by Jerry-zang** [comment]
@fuzhuang 
Hi Fuzhuang,
Happy Chinese New Year to you all! Thanks for the test and scenarios, may the coming new year bring you joy, love and peace!
Best Regards!

**Comment by fuzhuang** [comment]
Hi @Jerry-zang , thanks for all the replies.

Our HR @hazelwu will send you invitation to interview soon, keep tuned.

**Comment by Jerry-zang** [comment]
@fuzhuang 
Hi Fuzhuang,
Copy that, thanks for your information, hope I could learn more from you in the future!
@hazelwu 
Hi Hazel, this is Jerry, looking forward to your invitation and hope we can have a nice talk ,thanks!

**Comment by fuzhuang** [comment]
close as done
