### ISSUE TITLE
Test for Gunnar

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#5]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
You have been assigned as project manager for a project for the client Kuno Corp (your client stakeholder is Leo). The outcome of this project will be a website which allows a user to sign up, and log-in to a system that gives them real-time sales figures for their salesmen. The system as a whole is expected in 5 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for login and signup as well as the frontend for real-time sales figure information - This will be handled by Wiredcraft completely
• the backend for real-time sales figure information which will be provided by a separate company Jhonny Labs, you will need to interface with Frank, their project manager, to coordinate as they are building this system from scratch for Kuno Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the real-time sales figure information system expects to receive the Username and Email so they can customise the information in the backend for WCL to access and display in the front-end.

In your team you have:
• Two designers who can make mockups and flow diagrams of the login and once confirmed, implement the frontend parts.
• A developer who can implement the backend and help out integrating the login/sales figure frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Jhonny Labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@leo111) and real-time sales figure service vendor (@flfrank222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@leo111 - I heard from FLFrank222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by dulhaver** [comment]
@mpathiuk - can you clarify on those questions below about the test please?

- _front end for sales figure information system_ is the part of the website where the user can access the _sales figure data_ after login, correct?
- What is WCL?
- WC's team has 2 Designers. I assume "Designer" means "frontend developer", building the user interface. They design the detailed functionality, write the website's code and design the final aesthetical appearance of the website/interface. Is that so?

**Comment by mpathiuk** [comment]
> front end for sales figure information system is the part of the website where the user can access the sales figure data after login, correct?

Yes correct,

> What is WCL?
Wiredcraft Limited ,  our company abbreviation :)

> WC's team has 2 Designers. I assume "Designer" means "frontend developer", building the user interface. They design the detailed functionality, write the website's code and design the final aesthetical appearance of the website/interface. Is that so?

Yes correct, you have two designers who can make mockups and flow diagrams of the login and once confirmed, implement the frontend parts.

**Comment by dulhaver** [comment]
### Project Goal

Create a website which allows a user to sign up, log-in to a system that gives them real-time accesss to sales figures of their salesmen.

This is being done in cooperation with the Client "Kuno Corp" on one hand and "Jhonny Labs", who are building the _sales figure system_'s backend, on the other.


### WLC's mission

1. create back- and frontend for signup and login
2. create frontend for _sales figure information system_
3. co-ordinate integration _backend sales figure information system_ with Jhonny Labs

The system as a whole is expected in 5 weeks.

**Comment by dulhaver** [comment]
### First Action Steps

0. **create a git repository** for the project and add @myteam333, @flfrank222, @leo111
1. **confirm feature list** with Kuno Corp (cc: Jhonny labs)
2. inquire with Jhonny Labs **which data** exactly is being provided by _real-time sales figure system_
3. inquire **format of data** provided by _real-time sales figure system_ & get a set of **mock up data** WLC team will use while building our part
4. **draft a devops environment** with @myteam333 and ask devops to provide such, so we can always see our current system
5. **break down feature requirements into tasks** and (in coordination with Kuno Corp) prioritize them (aka build a backlog)

@mpathiuk @fuzhuang

**Comment by dulhaver** [comment]
### Running the Project

1. **evaluate tasks related to each other in terms of effort/time required** to finish with the team (each members does that individually in order to not compromise estimate through interference from others. Then we'll take the average values of these estimations.
2. **define length of sprints**. On the scenario given 1 week sprints seem to make sense
3. **team members pick their tasks** from top or backlog for the first sprint
4. perform **daily standup (10-15 min)** each morning (_'what did I do yesterday', 'what will I do today', 'what stands in my way to complete my tasks efficiently'_)
5. at the end of each sprint **present the running software to stakeholders** and anyone else interested.
Depending on how long a build process may take tasks should be finalized beforehand.
This can be done remotely if Client is unavailable for physical presence and possible technically (which for a website shouldn't be a problem)
6. at the end of sprint 1 **line out more detailed schedule for expected deliverables** (based on experience regarding progress from spring 1)

**Comment by dulhaver** [comment]
All **communication** between the WLC team, project stakeholders (Jhonny Labs, Kuno Corp.) is being **conducted through github issues** (assuming we give access to our repository to stakeholders).

**Comment by dulhaver** [comment]
@leo111 - can we go through more detailed feature requirements for the _real time sales figure system_ sometime please? Furthermore I'd like to prioritize those with you in order to structure deliverables from our end.

**Comment by dulhaver** [comment]
@leo111 - how is the status of the backend development for **Kuno Corps** _real time sales figure system_ on your end?

Furthermore I'd like to understand in more detail which exact data your system is going to produce and how this data will be accessible to the frontend side of this. Can we connect to real or mockup data alreay? 

I'd like my colleague Song Sun from our infrastructure team to clarify the technical details with your side, so we can either connect to your running system or create some mock up dataset for us to work with. Please let me know who he can contact on your side about this.

**Comment by dulhaver** [comment]
hi @mpathiuk, @fuzhuang, 
I haven't heard anything from you in this regards and was wondering whether you have any comments on this.

**Comment by fuzhuang** [comment]
Yes！Some new things happened to your project @vrms :

• Leo came to you and asked for 2 new diagrams for sales KPI info to be shown on the system interface;
• Your dev team is progressing slower than plan since the API provided from Johnny Lab is not stable
• Your dev-ops guys is taking a leave for a week with short notice due to family situation.

**Comment by dulhaver** [comment]
@LEO111 - all noted about the requested diagrams. When are you available to prioritize them against the other remaining features? 

Based on that we will get an idea how much these additions will influence the final delivery date.

**Comment by dulhaver** [comment]
### issue with API stability

**@myteam333** - as you may have noticed Johnny Labs is having some **issues with stability of the API** for the backend of the sales figure system we are building for Kuno. To adapt to this I'd need some input from your end.

- is that a problem for us at all? I mean we have attempted to set up a mockup. **Can we continue to work with that mockup for now and likewise just keep going?**
- In case we **do** depend on the API to be running I think we should focus on the graphical part of the frontend for now and get back to the functional coding once API is being ready to go. Does that make sense from your perspective?

I will talk to the customer based on your feedback accordingly

**Comment by dulhaver** [comment]
@LEO111 - I guess you have heard from **@flfrank222** about their problems with the stability of the API (the connector between the user interface which we are building to the system interiors build by Johnny Labs). 

I am discussing with the Wiredcraft team how much this disturbs to proceeding with the frontend/interface now and will get back to you about this shortly.

**Comment by dulhaver** [comment]
**@flfrank222** - Can you kindly give us an estimation when the API is expected to be stable?

**Comment by dulhaver** [comment]
(@fuzhuang - _will you play the role of **my team**, as well as **Frank** and provide the feedback as per above questions in their name, or should I assume their feedback myself in order to proceed here?_)

**Comment by dulhaver** [comment]
_(dev-ops guys is taking a leave for a week with short notice due to family situation.)_

**@myteam333** Song Sun is going to be on a leave for a week. I don't think we will be able to get a sub for him from the other teams on that short notice so we'll have to manage required building on our own while he is away. 

Is anybody familiar with the specific build scripts/workflow  being used for our project here?  

**@ sunsongxp** can you please provide a short how-to before you go?

**Comment by mpathiuk** [comment]
Thanks @vrms . We now have enough answers from this test to proceed to the next stage. Our Operations team will be in touch with you to coordinate.
