### ISSUE TITLE
Test for Pauline

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#6]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

Project Introduction
You have been assigned as project manager for a project for the client Makara Corp (your client stakeholder is Chopper). The outcome of this project will be an app which allows a user to sign up with SMS verification (input your phone number, receive an SMS with a special code and enter that code in the app to complete registration), and log-in to an existing user-tracking system made by Wayne Labs. The system as a whole is expected in 8 weeks.

Project Details
The work has been divided into two parts:
• the backend and frontend for login and signup with SMS verification - This will be handled by Wiredcraft completely
• the backend and frontend for the existing  user-tracking system which will be provided by a separate company Wayne Labs, you will need to interface with Kate, their project manager, to coordinate as they are maintaining the existing system from for Makara Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields as well as SMS validated phone number. The login will be based on username or phone number. And after sign up the existing system expects to receive the Username and Email so they can customise the information.

In your team you have:
• A designer who can make mockups and flow diagrams of the login and registration with SMS validation and once confirmed, implement the frontend.
• A developer who can implement the backend and help out integrating the login frontend.
• A dev-ops engineer who can set up the servers and take care of deployment.

Your Task

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the final scope for Wiredcraft's work.
• An initial project plan including:

• A work breakdown for Wiredcraft's integration with Wayne Labs up to the final delivery
a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
• Outline the project phases you would have and what should be delivered at each phase.
The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
• A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally.
• You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@chopper111) and existing service vendor (@kate222) ) and you can @myteam333 for questions to your development team)

e.g.
@chopper111 - Hi there, can I confirm with you the requirements for ...
@kate222 - I heard from chopper111 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by PaulinevDuin** [comment]
@Kate222 - Hi Kate, hope everything is going well on your side of the application! I was wondering if you and your team have time to meet on a weekly basis with our team? I want to make sure we will be able to implement our features and functions immediately in your already existing application without any complications, so a weekly update meeting and possible test would be very helpful. What do you think?

Furthermore, do you require the app to be responsive only on a mobile phone (apple, android) or also on tablets and PC's?

I hope to hear from you soon, 
Pauline

@Chopper111 - Hi Chopper, I hope you're well. I am just about to finalize our project requirements and planning and have a few questions which I hoped you could help me with:
- Should a user be able to change their details after they have signed-up in the app, or is this organized by the Wayne labs team?
- If a user forgets their password, should we create password change page? We could use the same SMS verification to validate their identity and then a new frame where they can change and confirm their new password. 
- Are their any other validations and restrictions we should keep in mind for the information? E.g. necessary special characters for the password requirements, length of a username, etc. 

Looking forward to your reply,
Pauline

@Myteam333 - Hi team, could one of you explain me more about the set-up time and requirements for implementing an SMS verification? Do we need any special features or functionalities that can stand in the way of our planning? 

I am also planning weekly update and test meetings with Wayne Labs, to support us in making sure we will be able to implement it without further complications. Could you tell me if we will be able to start integrating and testing our app from the first sprint deliveries (for example a working login-page)? 

Cheers, 
Pauline

**Comment by PaulinevDuin** [comment]
**Project scope**
WiredCraft has been assigned to help Makara Corp to produce and implement an application which can be fully integrated in their already existing user-tracking system. The function of the application is to make it possible for users to sign up for the user-tracking system and once signed up to login into the system with their defined details. One of the most important features of the application will be the verification process, where an SMS text message with a code is send to the user to confirm their details. The application will be interacting with the User-tracking system to exchange and update information. WiredCraft will be cooperating with Wayne Labs to coordinate the integration between the two systems. The finished product will be a fully working and integrated signup/in system for their user-tracking system. 

**Project breakdown**
For this project we will use Scrum as a project management methodology as this will give our client a transparent view of the progress we are making. I have broken down the project timeline into sprints of each 1 week, starting with an initial 6 weeks. Each sprint will start with a meeting in which the sprint deliverables are being discussed and end with a demo, evaluation and sprint review to make sure the following sprint has the right set of deliverables and that these can be implemented within that timeframe.  

Besides the sprint meetings there will also be daily scrum meeting to review the work done, any risks and constraints and the work to be done that day, this will keep the team on point and give the chance set a time to discuss issues and concerns during that day. 

The initial deliverable are set out in the following table, these deliverables are fluid and will be adjusted according to the process as explained before. The deliverables are set out based on priority, where the sign-up page with the SMS verification has the highest priority. 

_**Sprint 1**_	Initiation and Design	
-	A design of the front-end pages and the flow of the registration and log in. (wireframes)
-	A server will be chosen and set up. 
-	The dev-ops and developer will do their first test of working with Wayne labs back-end, to make sure our back-end will be compatible.	

_Initial deliverables_
D-001 Wireframes of front-end
D-002 A compatible back-end structure for future implementation. 

**_Sprint 2_**	Implement and validate
-	Create the front-end of the sign-up pages. 
-	Create the back-end of the sign-up procedures.	

_Initial deliverables_
D-003 Working Front-end and back-end that can receive and send information. 

_**Sprint 3**_	Implement and validate	
-	A working SMS verification in the back-end (a generated unique code can be requested and sent to a mobile phone number) 

_Initial deliverables_
D-004 An SMS verification system in the back-end. 

**_Sprint 4_**	Implement and validate	
-	Integrate the SMS verification with the front-end. 
- Integrate Sign-up procedure with Wayne labs	

_Initial deliverables_
D-004 An SMS verification system implemented in the front-end including validations. 

_**Sprint 5**_	Implement and validate	
-	Create the front-end of the login-up pages. 
-	Create the back-end of the login-up procedures.
-	Integrate Login-up procedure with Wayne labs	

_Initial deliverables_
D-005 Working Front-end and back-end that can receive and send information and integrated with the Wayne Labs system. 

**_Sprint 6_**	Validation and review	
-	Deployment and final integration of the application	

_Initial deliverables_
D-006 A working application which is integrated with the Wayne labs system.

**Documentation**
The _sprint meetings_ will have the following project management deliverables to keep track of the project status:
-	Updated requirements list based on the evaluation and demo
-	Updated bug list based on the demo
-	Minutes including the discussion points and conclusions, finalized into a confirmed sprint deliverables list. 

The _requirements_ will be organized according to the below, in an excel file that will be updated on a daily basis, the client will receive a copy by email at each sprint:
-	Deliverables: D-001 to D-999
-	User stories: U-001 to U-999
-	Bugs: B-001 to B-999

Internally all requirements are being kept track of via Trello. Trello is a flexible _project management tool_ which allows the team to use one "board" to keep track of tasks. As the PM I will input all the requirements, bugs and user stories and organize the board with 5 columns: "Deliverables", "Requirements", "Bugs", "Work in progress", "Testing" and "Done Sprint #". The team members will update their own assigned cards according to their progress. This will create full transparency to the team. 

_Documentation version tracking_ will be done via Github.

**External Communication**
Daily communication will be handled by the Project Manager of WiredCraft and will usually go via email or Github. There will be weekly sprint meetings organized together with Makara Corp to review the status and process. WiredCraft will work tightly with the Wayne Labs team and have weekly meetings and testing moments to keep track of the progress. Wayne Labs will also biweekly be invited to the sprint meetings to align all parties. Documentation will be updated regularly into github, so the Makara Corp, Wayne Labs and the team can access this at all times.

**Comment by PaulinevDuin** [comment]
@mpathiuk - Hi Mik, just wanted to check in with you if there were any comments to the above. Would love to hear if you'd like me to be more detailed on certain aspects or if there are any parts missing. Thanks and look forward to hearing from you. 
Regards, Pauline

**Comment by fuzhuang** [comment]
@PaulinevDuin Hi, a few additional situations come up for your project:

• During client QA, they found out the sign-in is not available, and your team's investigation shows that Wayne Lab changes the user ID digits specs without informing you guys.

• @chopper111 came to you, 2 days before the release, that due to marketing team arrangement, large scale marketing event will happen during the release date and thus they would like to separate the release into 2 phases, SMS validation will be released in a later date and the rest still going for the original plan.

**Comment by PaulinevDuin** [comment]
@kate222 - HI Kate, we were testing our demo and found out that some user ID digits specs changes have affected our sign-in. Currently it's not available which we hope to solve quickly. Could we schedule a meeting or Skype call to discuss how we can set up an automatic communication of user changes between the user-tracking system and the login? Then we can make sure our systems are always up to date, and users can have access to the tracking system without trouble. 

Let me know your thoughts, 
regards, 
Pauline

@myteam333 - Hi Team! I'm happy to say we are still on schedule, great! I've just spoken to Chopper and he has indicated he would like to have some slight changes in what to release when. Let's have a quick meeting in about 10 minutes to discuss and see the best way to move forward. Then I will send a proposal to Chopper with the details after. 

@chopper111 - Hi Chopper, glad we spoke today, I understand you would like to split up the SMS verification and the rest of the log-in into two separate release dates. I think it's a good idea, but we need to keep in mind that we set up some sort of validation of the data. As you can imagine, without verification, anybody can sign up and can even create multiple and fake accounts, which will influence the data you are collecting to track your users. I was considering a quick email verification, what do you think?

Regarding the timeline, I estimate that we can release the SMS verification one week later, in Sprint 9,, would that work for you as a release date?

Furthermore, as we have to delay our release a little bit and we need to consider some extra work on the back-end to separate the two parts, I have set up a proposal for the extra cost based on my time estimation. Please see it below and let me know if you have any comments. 
_Proposal_

Looking forward to your feedback and of course to the release in two days!
Kind regards, 
Pauline

**Comment by mpathiuk** [comment]
Thanks @PaulinevDuin . We have enough info in this test to proceed to the next stage. Our Operations team will be in touch with you to coordinate.

**Comment by mpathiuk** [comment]
Moved to next stage, closing as done.
